Python 3 Apple:
  script:
  - py_version=3
  - EXTRA_INSTALL="numpy mako"
  - export PYFMMLIB_BUILD_MODE=setuptools
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - apple
  - python3
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml

Python 3:
  script:
  - py_version=3
  - EXTRA_INSTALL="numpy mako"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python3
  - gfortran
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml
