Python 2.7:
  script:
  - py_version=2.7
  - EXTRA_INSTALL="numpy mako"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python2.7
  - gfortran
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml

Python 2.7 Apple:
  script:
  - py_version=2.7
  - EXTRA_INSTALL="numpy mako"
  - export PYFMMLIB_BUILD_MODE=setuptools
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - apple
  - python2.7
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml

Python 3.6:
  script:
  - py_version=3.6
  - EXTRA_INSTALL="numpy mako"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python3.6
  - gfortran
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml

Python 3.7:
  script:
  - py_version=3.7
  - EXTRA_INSTALL="numpy mako"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python3.7
  - gfortran
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml
