jobs:
-
    job: 'Pytest'
    pool:
        vmImage: 'ubuntu-latest'
    strategy:
        matrix:
            Python27:
                python.version: '2.7'
            Python36:
                python.version: '3.6'
            Python37:
                python.version: '3.7'

    steps:
    -
        task: UsePythonVersion@0
        inputs:
            versionSpec: '$(python.version)'

    -
        script: |
            set -e
            EXTRA_INSTALL="numpy mako"
            sudo apt install gfortran-7
            sudo ln -s /usr/bin/gfortran-7 /usr/bin/gfortran
            curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
            . ./build-and-test-py-project.sh

        displayName: 'Pytest'

    -
        task: PublishTestResults@2
        inputs:
            testResultsFormat: 'JUnit'
            testResultsFiles: 'test/pytest.xml'

schedules:
-
    cron: "0 0 * * 0"
    displayName: Weekly build
    branches:
        include:
        - master
